**Series - 1D array**

In [2]:
import pandas as pd

marks = pd.Series([10,45,34,62,29,43.5,"pakistan"])
print(marks)
print(marks[6])

0          10
1          45
2          34
3          62
4          29
5        43.5
6    pakistan
dtype: object
pakistan

In [3]:
print(marks.index)

RangeIndex(start=0, stop=7, step=1)

In [4]:
result = pd.Series([10,45,34,62,29,43], index=["Ali","Sara","Farooq","Ahmad","Javed","Imran"])
print(result)
print(result['Farooq'])

Ali       10
Sara      45
Farooq    34
Ahmad     62
Javed     29
Imran     43
dtype: int64
34

In [5]:
print(result.index)
print(result.values)

Index(['Ali', 'Sara', 'Farooq', 'Ahmad', 'Javed', 'Imran'], dtype='str')
[10 45 34 62 29 43]

**Series using Dictionaries**

In [6]:
st_marks = pd.Series({"Ali":10,"Sara":45,"Farooq":34,"Ahmad":62,"Javed":29,"Imran":43})
print(st_marks)
print(st_marks['Ahmad'])
print(st_marks.iloc[3])

Ali       10
Sara      45
Farooq    34
Ahmad     62
Javed     29
Imran     43
dtype: int64
62
62

In [7]:
print(st_marks.iloc[1:3])

Sara      45
Farooq    34
dtype: int64

In [8]:
print(st_marks[['Farooq','Javed']]+5)

Farooq    39
Javed     34
dtype: int64

0h:23m <br>
**DataFrame  - Rows and Columns** <br>
- A **DataFrame** is a full table

In [9]:
students = pd.DataFrame({
            "name":["Ali","Ahmad","Usman","Javed","Farooq"],
            "age":[17,19,24,21,18],
            "city":["karachi","lahore","multan","islamabad","quetta"],
            "marks":[45,54,56,43,67]
    })

print(students)

#to retrieve a column
print(students['city'])

#to retrieve a row
print(students.iloc[0])

     name  age       city  marks
0     Ali   17    karachi     45
1   Ahmad   19     lahore     54
2   Usman   24     multan     56
3   Javed   21  islamabad     43
4  Farooq   18     quetta     67
0      karachi
1       lahore
2       multan
3    islamabad
4       quetta
Name: city, dtype: str
name         Ali
age           17
city     karachi
marks         45
Name: 0, dtype: object

In [10]:
print(f"Dataframe has {students.shape[0]} rows and {students.shape[1]} columns")
print(students.ndim)
print(students.size)
print(students.dtypes)
print(students.columns)
print(students.index)

Dataframe has 5 rows and 4 columns
2
20
name       str
age      int64
city       str
marks    int64
dtype: object
Index(['name', 'age', 'city', 'marks'], dtype='str')
RangeIndex(start=0, stop=5, step=1)

In [11]:
r,c = students.shape
print(f"{r} rows {c} columns")
print(students.info())

5 rows 4 columns
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   city    5 non-null      str
 3   marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes
None

0h:46m <br>
**Loading real data**
1. **From a .CSV file** <br>
    df = pd.read_csv() <br>
2. **From built-in sample dataset** (needs `seaborn` library) <br>
    df = sns.load_dataset("titanic")

In [12]:
import seaborn as sns
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [13]:
ds_titanic = sns.load_dataset("titanic")
print(ds_titanic.shape)
print(ds_titanic.columns)
print(ds_titanic.info())

(891, 15)
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None

In [14]:
ds_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
print(ds_titanic.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [16]:
#prints first 5 rows
ds_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
#prints last 5 rows
ds_titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [18]:
#prints first 10 rows
ds_titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [19]:
ds_titanic.tail(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [20]:
#returns random 5 rows
ds_titanic.sample(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
446,1,2,female,13.0,0,1,19.5000,S,Second,child,False,NaN,Southampton,yes,False
804,1,3,male,27.0,0,0,6.9750,S,Third,man,True,NaN,Southampton,yes,True
615,1,2,female,24.0,1,2,65.0000,S,Second,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
563,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
812,0,2,male,35.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
810,0,3,male,26.0,0,0,7.8875,S,Third,man,True,NaN,Southampton,no,True
405,0,2,male,34.0,1,0,21.0000,S,Second,man,True,NaN,Southampton,no,False
670,1,2,female,40.0,1,1,39.0000,S,Second,woman,False,NaN,Southampton,yes,False

1h:18m <br>
- .describe()
- only describes numeric columns

In [21]:
ds_titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [22]:
#missing values's sum
ds_titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

1h:21m <br>
**Selecting Columns** <br>
- df['age'] - one set of square brackets - returns a series
- df[['age','fare']] - two sets - returns a dataframe

In [23]:
ages = ds_titanic['age']
print(ages.head())
print(f"Ages Mean: {round(ages.mean(),1)}")
print(f"Ages Median: {round(ages.median(),1)}")
print(f"Ages Max: {round(ages.max(),1)}")
print(f"Ages Min: {round(ages.min(),1)}")

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64
Ages Mean: 29.7
Ages Median: 28.0
Ages Max: 80.0
Ages Min: 0.4

In [33]:
over_30 = ages>30
males = ds_titanic['sex']=='male'
print(f"Males: {males.sum()}")
print(f"Over 30: {over_30.sum()}")
print(ds_titanic['sex'])

#find over 30 males
over_30_males = males & over_30
print(f"Over 30 Males Count: {over_30_males.sum()}")
print(f"Over 30 Males: {ds_titanic[over_30_males]}")

Males: 577
Over 30: 305
0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: str
Over 30 Males Count: 202
Over 30 Males:      survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
4           0       3  male  35.0      0      0   8.0500        S   Third
6           0       1  male  54.0      0      0  51.8625        S   First
13          0       3  male  39.0      1      5  31.2750        S   Third
20          0       2  male  35.0      0      0  26.0000        S  Second
21          1       2  male  34.0      0      0  13.0000        S  Second
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
867         0       1  male  31.0      0      0  50.4958        S   First
872         0       1  male  33.0      0      0   5.0000        S   First
873         0       3  male  47.0      0      0   9.0000        S   Third
881         0       3  male  33.0      0      0   7.8958        S   Third
890         0       3  male  32.0      0      0   7.7500        Q   Third

     who  adult_male deck  embark_town alive  alone
4    man        True  NaN  Southampton    no   True
6    man        True    E  Southampton    no   True
13   man        True  NaN  Southampton    no  False
20   man        True  NaN  Southampton    no   True
21   man        True    D  Southampton   yes   True
..   ...         ...  ...          ...   ...    ...
867  man        True    A  Southampton    no   True
872  man        True    B  Southampton    no   True
873  man        True  NaN  Southampton    no   True
881  man        True  NaN  Southampton    no   True
890  man        True  NaN   Queenstown    no   True

[202 rows x 15 columns]

**subset of dataset**

In [25]:
#filters columns
ds_titanic_sub1=ds_titanic[['survived','pclass','sex','age']]
print(ds_titanic_sub1)
#only males
ds_titanic_sub1[ds_titanic_sub1['sex']=='male']

     survived  pclass     sex   age
0           0       3    male  22.0
1           1       1  female  38.0
2           1       3  female  26.0
3           1       1  female  35.0
4           0       3    male  35.0
..        ...     ...     ...   ...
886         0       2    male  27.0
887         1       1  female  19.0
888         0       3  female   NaN
889         1       1    male  26.0
890         0       3    male  32.0

[891 rows x 4 columns]

     survived  pclass   sex   age
0           0       3  male  22.0
4           0       3  male  35.0
5           0       3  male   NaN
6           0       1  male  54.0
7           0       3  male   2.0
..        ...     ...   ...   ...
883         0       2  male  28.0
884         0       3  male  25.0
886         0       2  male  27.0
889         1       1  male  26.0
890         0       3  male  32.0

[577 rows x 4 columns]

In [26]:
print(f"Survival rate: {round(ds_titanic['survived'].mean(),2)}")

Survival rate: 0.38

In [27]:
print(ds_titanic['sex'].value_counts())
male,female = ds_titanic['sex'].value_counts()
print(f"There were {male} males and {female} females aboard on ship")

sex
male      577
female    314
Name: count, dtype: int64
There were 577 males and 314 females aboard on ship

In [28]:
sur_yes,sur_no=ds_titanic['survived'].value_counts()
ds_titanic['survived'].value_counts()
print(f"Survived: {sur_yes}")
print(f"Not Survived: {sur_no}")

Survived: 549
Not Survived: 342

In [29]:
print(ds_titanic['pclass'].value_counts())

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [30]:
ds_titanic['pclass'].value_counts(normalize=True)

pclass
3    0.551066
1    0.242424
2    0.206510
Name: proportion, dtype: float64

In [31]:
ds_titanic['sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [32]:
ds_titanic['sex'].nunique()
ds_titanic['age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])