In [5]:
import pandas as pd

a = pd.Series([1,2,3,4,5], index=["ali","irfan","ahmed","hassan","bilal"])
a

ali       1
irfan     2
ahmed     3
hassan    4
bilal     5
dtype: int64

In [6]:
b = pd.Series({"ali":1,"irfan":2, "ahmed":3, "hassan":4, "bilal":5})
b

ali       1
irfan     2
ahmed     3
hassan    4
bilal     5
dtype: int64

In [ ]:
c = pd.DataFrame({
    "name":["ali","irfan","ahmed","hassan","bilal"],
    "age":[20,21,22,23,24],
    "city":["karachi","lahore","islamabad","quetta","peshawar"],
    "marks":[90,80,70,60,50]
},
index=["a","b","c","d","e"]
)
print(c)
print(c.columns)
print(c.index)

     name  age       city  marks
a     ali   20    karachi     90
b   irfan   21     lahore     80
c   ahmed   22  islamabad     70
d  hassan   23     quetta     60
e   bilal   24   peshawar     50
Index(['name', 'age', 'city', 'marks'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [ ]:
bs_result = pd.read_csv("bs_english_2025.csv",delimiter=",")
bs_result.shape
bs_result.index
bs_result.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   student_name                          11 non-null     str
 1   father_name                           11 non-null     str
 2   18th_century_english_novel            11 non-null     int64
 3   islamic_studies                       11 non-null     int64
 4   understanding_holy_quran_1            11 non-null     int64
 5   history_of_english_literature         11 non-null     int64
 6   intro_to_literary_devices_and_genres  11 non-null     int64
 7   functional_english                    11 non-null     int64
 8   applications_of_ict                   11 non-null     int64
 9   obt_marks                             11 non-null     int64
 10  total_marks                           11 non-null     int64
 11  percentage_of_obt_marks               11 non-null     float64
 12  cr_hrs                                11 non-null     int64
 13  overall_cgpa                          11 non-null     float64
 14  remarks                               11 non-null     str
dtypes: float64(2), int64(10), str(3)
memory usage: 1.4 KB

,18th_century_english_novel,islamic_studies,understanding_holy_quran_1,history_of_english_literature,intro_to_literary_devices_and_genres,functional_english,applications_of_ict,obt_marks,total_marks,percentage_of_obt_marks,cr_hrs,overall_cgpa
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.0,11.000000,11.0,11.000000
mean,76.636364,81.545455,86.727273,68.818182,63.818182,62.545455,74.727273,514.818182,700.0,73.544545,18.0,3.339091
std,8.213072,6.470914,4.880387,8.623435,12.056684,10.033580,6.512924,41.373465,0.0,5.910478,0.0,0.421176
min,67.000000,74.000000,79.000000,55.000000,48.000000,43.000000,66.000000,456.000000,700.0,65.140000,18.0,2.710000
25%,69.000000,76.500000,85.000000,63.000000,53.000000,61.000000,69.000000,476.500000,700.0,68.070000,18.0,2.995000
50%,78.000000,78.000000,87.000000,67.000000,63.000000,62.000000,77.000000,515.000000,700.0,73.570000,18.0,3.400000
75%,83.000000,87.000000,89.000000,73.500000,75.000000,69.500000,80.000000,550.000000,700.0,78.570000,18.0,3.680000
max,90.000000,91.000000,96.000000,84.000000,81.000000,77.000000,84.000000,572.000000,700.0,81.710000,18.0,3.860000

In [20]:
bs_result.describe()

,18th_century_english_novel,islamic_studies,understanding_holy_quran_1,history_of_english_literature,intro_to_literary_devices_and_genres,functional_english,applications_of_ict,obt_marks,total_marks,percentage_of_obt_marks,cr_hrs,overall_cgpa
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.0,11.000000,11.0,11.000000
mean,76.636364,81.545455,86.727273,68.818182,63.818182,62.545455,74.727273,514.818182,700.0,73.544545,18.0,3.339091
std,8.213072,6.470914,4.880387,8.623435,12.056684,10.033580,6.512924,41.373465,0.0,5.910478,0.0,0.421176
min,67.000000,74.000000,79.000000,55.000000,48.000000,43.000000,66.000000,456.000000,700.0,65.140000,18.0,2.710000
25%,69.000000,76.500000,85.000000,63.000000,53.000000,61.000000,69.000000,476.500000,700.0,68.070000,18.0,2.995000
50%,78.000000,78.000000,87.000000,67.000000,63.000000,62.000000,77.000000,515.000000,700.0,73.570000,18.0,3.400000
75%,83.000000,87.000000,89.000000,73.500000,75.000000,69.500000,80.000000,550.000000,700.0,78.570000,18.0,3.680000
max,90.000000,91.000000,96.000000,84.000000,81.000000,77.000000,84.000000,572.000000,700.0,81.710000,18.0,3.860000

In [25]:
#performance tiering 
#student between 3.5 to 4
best_performers = bs_result[bs_result['overall_cgpa']>3.5]
bp=best_performers.nlargest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
bp

,student_name,overall_cgpa,obt_marks,total_marks,percentage_of_obt_marks
5,ruqiya noreen,3.86,572,700,81.71
3,sidra kainat,3.82,562,700,80.29
2,shameen iqbal,3.77,551,700,78.71
1,aiman laraib,3.59,530,700,75.71
6,jamila bibi,3.57,549,700,78.43

In [ ]:
worst_performers = bs_results.nsmallest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
worst_performers