In [72]:
import pandas as pd

a = pd.Series([12,2,23,14,5], index=["ali","irfan","ahmed","hassan","bilal"])
a.sort_values(ascending=False)
type(a)

pandas.Series

In [56]:
b = pd.Series({"ali":10,"irfan":12, "ahmed":31, "hassan":14, "bilal":5})
b.sort_values(ascending=False)

ahmed     31
hassan    14
irfan     12
ali       10
bilal      5
dtype: int64

In [50]:
c = pd.DataFrame({
    "name":["ali","irfan","ahmed","hassan","bilal"],
    "age":[20,21,22,23,24],
    "city":["karachi","lahore","islamabad","quetta","peshawar"],
    "marks":[90,80,70,60,50]
},
index=["a","b","c","d","e"]
)
print(c)
print(c.columns)
print(c.index)
print(c.sort_values(by="marks"))

     name  age       city  marks
a     ali   20    karachi     90
b   irfan   21     lahore     80
c   ahmed   22  islamabad     70
d  hassan   23     quetta     60
e   bilal   24   peshawar     50
Index(['name', 'age', 'city', 'marks'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
     name  age       city  marks
e   bilal   24   peshawar     50
d  hassan   23     quetta     60
c   ahmed   22  islamabad     70
b   irfan   21     lahore     80
a     ali   20    karachi     90

In [4]:
bs_result = pd.read_csv("bs_english_2025.csv",delimiter=",")
bs_result.shape
bs_result.index
bs_result.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   student_name                          11 non-null     str
 1   father_name                           11 non-null     str
 2   18th_century_english_novel            11 non-null     int64
 3   islamic_studies                       11 non-null     int64
 4   understanding_holy_quran_1            11 non-null     int64
 5   history_of_english_literature         11 non-null     int64
 6   intro_to_literary_devices_and_genres  11 non-null     int64
 7   functional_english                    11 non-null     int64
 8   applications_of_ict                   11 non-null     int64
 9   obt_marks                             11 non-null     int64
 10  total_marks                           11 non-null     int64
 11  percentage_of_obt_marks               11 non-null     float64
 12  cr_hrs                                11 non-null     int64
 13  overall_cgpa                          11 non-null     float64
 14  remarks                               11 non-null     str
dtypes: float64(2), int64(10), str(3)
memory usage: 1.4 KB

In [102]:

df = bs_result.describe()
print(df)
round(df.iloc[1,0:7],2).sort_values(ascending=False)

# df['18th_century_english_novel']

       18th_century_english_novel  islamic_studies  \
count                   11.000000        11.000000
mean                    76.636364        81.545455
std                      8.213072         6.470914
min                     67.000000        74.000000
25%                     69.000000        76.500000
50%                     78.000000        78.000000
75%                     83.000000        87.000000
max                     90.000000        91.000000

       understanding_holy_quran_1  history_of_english_literature  \
count                   11.000000                      11.000000
mean                    86.727273                      68.818182
std                      4.880387                       8.623435
min                     79.000000                      55.000000
25%                     85.000000                      63.000000
50%                     87.000000                      67.000000
75%                     89.000000                      73.500000
max                     96.000000                      84.000000

       intro_to_literary_devices_and_genres  functional_english  \
count                             11.000000           11.000000
mean                              63.818182           62.545455
std                               12.056684           10.033580
min                               48.000000           43.000000
25%                               53.000000           61.000000
50%                               63.000000           62.000000
75%                               75.000000           69.500000
max                               81.000000           77.000000

       applications_of_ict   obt_marks  total_marks  percentage_of_obt_marks  \
count            11.000000   11.000000         11.0                11.000000
mean             74.727273  514.818182        700.0                73.544545
std               6.512924   41.373465          0.0                 5.910478
min              66.000000  456.000000        700.0                65.140000
25%              69.000000  476.500000        700.0                68.070000
50%              77.000000  515.000000        700.0                73.570000
75%              80.000000  550.000000        700.0                78.570000
max              84.000000  572.000000        700.0                81.710000

       cr_hrs  overall_cgpa
count    11.0     11.000000
mean     18.0      3.339091
std       0.0      0.421176
min      18.0      2.710000
25%      18.0      2.995000
50%      18.0      3.400000
75%      18.0      3.680000
max      18.0      3.860000

understanding_holy_quran_1              86.73
islamic_studies                         81.55
18th_century_english_novel              76.64
applications_of_ict                     74.73
history_of_english_literature           68.82
intro_to_literary_devices_and_genres    63.82
functional_english                      62.55
Name: mean, dtype: float64

In [11]:
bs_result

,student_name,father_name,18th_century_english_novel,islamic_studies,understanding_holy_quran_1,history_of_english_literature,intro_to_literary_devices_and_genres,functional_english,applications_of_ict,obt_marks,total_marks,percentage_of_obt_marks,cr_hrs,overall_cgpa,remarks
0,khadija javed,javed zafar,90,75,79,64,68,61,78,515,700,73.57,18,3.40,promoted
1,aiman laraib,ashfaq ahmed,82,74,86,74,74,63,77,530,700,75.71,18,3.59,promoted
2,shameen iqbal,muhammad zafar iqbal,84,78,84,73,76,72,84,551,700,78.71,18,3.77,promoted
3,sidra kainat,malik fazal ur rehman,82,76,90,84,81,67,82,562,700,80.29,18,3.82,promoted
4,sumaira bibi,malik khair muhammad,70,78,88,55,52,43,70,456,700,65.14,18,2.71,promoted
5,ruqiya noreen,attaullah khan,84,91,87,80,76,72,82,572,700,81.71,18,3.86,promoted
6,jamila bibi,rafiullah khan,78,91,96,67,63,77,77,549,700,78.43,18,3.57,promoted
7,sadia bibi,shujaudin,69,77,87,62,54,62,68,479,700,68.43,18,3.02,promoted
8,malik sheeraz,muhammad faiz ullah,69,88,88,72,62,61,70,510,700,72.86,18,3.25,promoted
9,muhammad zain ahad,israr muhammad amjad,67,86,79,64,48,62,68,474,700,67.71,18,2.97,promoted
10,aimal aslam,muhammad aslam,68,83,90,62,48,48,66,465,700,66.43,18,2.77,promoted

In [9]:
#performance tiering 
#student between 3.5 to 4
#best_performers = bs_result[bs_result['overall_cgpa']>3.5]
best_performers = bs_result.nlargest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
best_performers

,student_name,overall_cgpa,obt_marks,total_marks,percentage_of_obt_marks
5,ruqiya noreen,3.86,572,700,81.71
3,sidra kainat,3.82,562,700,80.29
2,shameen iqbal,3.77,551,700,78.71
1,aiman laraib,3.59,530,700,75.71
6,jamila bibi,3.57,549,700,78.43

In [8]:
worst_performers = bs_result.nsmallest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
worst_performers

,student_name,overall_cgpa,obt_marks,total_marks,percentage_of_obt_marks
4,sumaira bibi,2.71,456,700,65.14
10,aimal aslam,2.77,465,700,66.43
9,muhammad zain ahad,2.97,474,700,67.71
7,sadia bibi,3.02,479,700,68.43
8,malik sheeraz,3.25,510,700,72.86

In [ ]:
#students with most failed subjects


#difficult subjects

#easy subjects

#best performaning subjects
#worst performing subjects

In [ ]:
# print(len(bs_result.columns))
# print(len(bs_result.columns))
data =[]
d_index=[]
col = bs_result.columns
print("Subjects|                          |Average Marks|")
for m in range(2,9):
  # print(f"{col[m]} {round(bs_result[col[m]].mean(),2)}")
  data.append(round(bs_result[col[m]].mean(),2))
  d_index.append(col[m])

sub = pd.Series(data,index=d_index)
print(sub.sort_values(ascending=False))

Subjects|                       |Average Marks|
understanding_holy_quran_1              86.73
islamic_studies                         81.55
18th_century_english_novel              76.64
applications_of_ict                     74.73
history_of_english_literature           68.82
intro_to_literary_devices_and_genres    63.82
functional_english                      62.55
dtype: float64

In [108]:
bs_result.nlargest(5,"understanding_holy_quran_1")[['student_name','understanding_holy_quran_1']]

     student_name  understanding_holy_quran_1
6     jamila bibi                          96
3    sidra kainat                          90
10    aimal aslam                          90
4    sumaira bibi                          88
8   malik sheeraz                          88

In [ ]:
data =[]
d_index=[]
col = bs_result.columns
print("__________|Subjects|_________________| Failed Students|_____")
for m in range(2,9):
  # print(f"{col[m]} {round(bs_result[col[m]].mean(),2)}")
  fa = bs_result[bs_result[col[m]]<50]
  data.append(fa.shape[0])
  d_index.append(col[m])

sub = pd.Series(data,index=d_index)
print(sub.sort_values(ascending=False))

__________|Subjects|_________________| Failed Students|_____
intro_to_literary_devices_and_genres    2
functional_english                      2
18th_century_english_novel              0
understanding_holy_quran_1              0
islamic_studies                         0
history_of_english_literature           0
applications_of_ict                     0
dtype: int64

students ----> # of failed subjects